[tool.ruff]
line-length = 120
include = ["*.py", "*.pyi", "**/pyproject.toml"]

[tool.ruff.lint]
select = ["D102", "F401"]

[tool.ruff.lint.isort]
case-sensitive = true
relative-imports-order = "closest-to-furthest"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.pylint]
max-line-length = 120

[tool.mypy]
ignore_missing_imports = false
